// <auto-generated />
using DoyaDoyaAnadolu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoyaDoyaAnadolu.Migrations
{
    [DbContext(typeof(TurkiyeContext))]
    partial class TurkiyeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoyaDoyaAnadolu.Data.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BolgeAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BolgeAd = "Akdeniz Bölgesi"
                        },
                        new
                        {
                            Id = 2,
                            BolgeAd = "Doğu Anadolu Bölgesi"
                        },
                        new
                        {
                            Id = 3,
                            BolgeAd = "Ege Bölgesi"
                        },
                        new
                        {
                            Id = 4,
                            BolgeAd = "Güneydoğu Anadolu Bölgesi"
                        },
                        new
                        {
                            Id = 5,
                            BolgeAd = "İç Anadolu Bölgesi"
                        },
                        new
                        {
                            Id = 6,
                            BolgeAd = "Karadeniz Bölgesi"
                        },
                        new
                        {
                            Id = 7,
                            BolgeAd = "Marmara Bölgesi"
                        });
                });

            modelBuilder.Entity("DoyaDoyaAnadolu.Data.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<int>("Nufus")
                        .HasColumnType("int");

                    b.Property<string>("SehirAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.ToTable("Sehirler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BolgeId = 1,
                            Nufus = 2201670,
                            SehirAd = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            BolgeId = 4,
                            Nufus = 610484,
                            SehirAd = "Adıyaman"
                        },
                        new
                        {
                            Id = 3,
                            BolgeId = 3,
                            Nufus = 714523,
                            SehirAd = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = 4,
                            BolgeId = 2,
                            Nufus = 542255,
                            SehirAd = "Ağrı"
                        },
                        new
                        {
                            Id = 5,
                            BolgeId = 6,
                            Nufus = 326351,
                            SehirAd = "Amasya"
                        },
                        new
                        {
                            Id = 6,
                            BolgeId = 5,
                            Nufus = 5346518,
                            SehirAd = "Ankara"
                        },
                        new
                        {
                            Id = 7,
                            BolgeId = 1,
                            Nufus = 2328555,
                            SehirAd = "Antalya"
                        },
                        new
                        {
                            Id = 8,
                            BolgeId = 6,
                            Nufus = 168068,
                            SehirAd = "Artvin"
                        },
                        new
                        {
                            Id = 9,
                            BolgeId = 3,
                            Nufus = 1068260,
                            SehirAd = "Aydın"
                        },
                        new
                        {
                            Id = 10,
                            BolgeId = 7,
                            Nufus = 1196176,
                            SehirAd = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            BolgeId = 7,
                            Nufus = 218297,
                            SehirAd = "Bilecik"
                        },
                        new
                        {
                            Id = 12,
                            BolgeId = 2,
                            Nufus = 269560,
                            SehirAd = "Bingöl"
                        },
                        new
                        {
                            Id = 13,
                            BolgeId = 2,
                            Nufus = 341225,
                            SehirAd = "Bitlis"
                        },
                        new
                        {
                            Id = 14,
                            BolgeId = 6,
                            Nufus = 299896,
                            SehirAd = "Bolu"
                        },
                        new
                        {
                            Id = 15,
                            BolgeId = 1,
                            Nufus = 261401,
                            SehirAd = "Burdur"
                        },
                        new
                        {
                            Id = 16,
                            BolgeId = 7,
                            Nufus = 2901396,
                            SehirAd = "Bursa"
                        },
                        new
                        {
                            Id = 17,
                            BolgeId = 7,
                            Nufus = 519793,
                            SehirAd = "Çanakkale"
                        },
                        new
                        {
                            Id = 18,
                            BolgeId = 5,
                            Nufus = 183880,
                            SehirAd = "Çankırı"
                        },
                        new
                        {
                            Id = 19,
                            BolgeId = 6,
                            Nufus = 527863,
                            SehirAd = "Çorum"
                        },
                        new
                        {
                            Id = 20,
                            BolgeId = 3,
                            Nufus = 1005687,
                            SehirAd = "Denizli"
                        },
                        new
                        {
                            Id = 21,
                            BolgeId = 4,
                            Nufus = 1673119,
                            SehirAd = "Diyarbakır"
                        },
                        new
                        {
                            Id = 22,
                            BolgeId = 7,
                            Nufus = 401701,
                            SehirAd = "Edirne"
                        },
                        new
                        {
                            Id = 23,
                            BolgeId = 2,
                            Nufus = 578789,
                            SehirAd = "Elazığ"
                        },
                        new
                        {
                            Id = 24,
                            BolgeId = 2,
                            Nufus = 226032,
                            SehirAd = "Erzincan"
                        },
                        new
                        {
                            Id = 25,
                            BolgeId = 2,
                            Nufus = 762021,
                            SehirAd = "Erzurum"
                        },
                        new
                        {
                            Id = 26,
                            BolgeId = 5,
                            Nufus = 844842,
                            SehirAd = "Eskişehir"
                        },
                        new
                        {
                            Id = 27,
                            BolgeId = 4,
                            Nufus = 1974244,
                            SehirAd = "Gaziantep"
                        },
                        new
                        {
                            Id = 28,
                            BolgeId = 6,
                            Nufus = 444467,
                            SehirAd = "Giresun"
                        },
                        new
                        {
                            Id = 29,
                            BolgeId = 6,
                            Nufus = 172034,
                            SehirAd = "Gümüşhane"
                        },
                        new
                        {
                            Id = 30,
                            BolgeId = 2,
                            Nufus = 267813,
                            SehirAd = "Hakkari"
                        },
                        new
                        {
                            Id = 31,
                            BolgeId = 1,
                            Nufus = 1555165,
                            SehirAd = "Hatay"
                        },
                        new
                        {
                            Id = 32,
                            BolgeId = 1,
                            Nufus = 427324,
                            SehirAd = "Isparta"
                        },
                        new
                        {
                            Id = 33,
                            BolgeId = 1,
                            Nufus = 1773852,
                            SehirAd = "Mersin"
                        },
                        new
                        {
                            Id = 34,
                            BolgeId = 7,
                            Nufus = 14804116,
                            SehirAd = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            BolgeId = 3,
                            Nufus = 4223545,
                            SehirAd = "İzmir"
                        },
                        new
                        {
                            Id = 36,
                            BolgeId = 2,
                            Nufus = 289786,
                            SehirAd = "Kars"
                        },
                        new
                        {
                            Id = 37,
                            BolgeId = 6,
                            Nufus = 376945,
                            SehirAd = "Kastamonu"
                        },
                        new
                        {
                            Id = 38,
                            BolgeId = 5,
                            Nufus = 1358980,
                            SehirAd = "Kayseri"
                        },
                        new
                        {
                            Id = 39,
                            BolgeId = 7,
                            Nufus = 351684,
                            SehirAd = "Kırklareli"
                        },
                        new
                        {
                            Id = 40,
                            BolgeId = 5,
                            Nufus = 229975,
                            SehirAd = "Kırşehir"
                        },
                        new
                        {
                            Id = 41,
                            BolgeId = 7,
                            Nufus = 1830772,
                            SehirAd = "Kocaeli"
                        },
                        new
                        {
                            Id = 42,
                            BolgeId = 5,
                            Nufus = 2161303,
                            SehirAd = "Konya"
                        },
                        new
                        {
                            Id = 43,
                            BolgeId = 3,
                            Nufus = 573642,
                            SehirAd = "Kütahya"
                        },
                        new
                        {
                            Id = 44,
                            BolgeId = 2,
                            Nufus = 781305,
                            SehirAd = "Malatya"
                        },
                        new
                        {
                            Id = 45,
                            BolgeId = 3,
                            Nufus = 1396945,
                            SehirAd = "Manisa"
                        },
                        new
                        {
                            Id = 46,
                            BolgeId = 1,
                            Nufus = 1112634,
                            SehirAd = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = 47,
                            BolgeId = 4,
                            Nufus = 796237,
                            SehirAd = "Mardin"
                        },
                        new
                        {
                            Id = 48,
                            BolgeId = 3,
                            Nufus = 923773,
                            SehirAd = "Muğla"
                        },
                        new
                        {
                            Id = 49,
                            BolgeId = 2,
                            Nufus = 406501,
                            SehirAd = "Muş"
                        },
                        new
                        {
                            Id = 50,
                            BolgeId = 5,
                            Nufus = 290895,
                            SehirAd = "Nevşehir"
                        },
                        new
                        {
                            Id = 51,
                            BolgeId = 5,
                            Nufus = 351468,
                            SehirAd = "Niğde"
                        },
                        new
                        {
                            Id = 52,
                            BolgeId = 6,
                            Nufus = 750588,
                            SehirAd = "Ordu"
                        },
                        new
                        {
                            Id = 53,
                            BolgeId = 6,
                            Nufus = 331048,
                            SehirAd = "Rize"
                        },
                        new
                        {
                            Id = 54,
                            BolgeId = 7,
                            Nufus = 976948,
                            SehirAd = "Sakarya"
                        },
                        new
                        {
                            Id = 55,
                            BolgeId = 6,
                            Nufus = 1295927,
                            SehirAd = "Samsun"
                        },
                        new
                        {
                            Id = 56,
                            BolgeId = 4,
                            Nufus = 322664,
                            SehirAd = "Siirt"
                        },
                        new
                        {
                            Id = 57,
                            BolgeId = 6,
                            Nufus = 205478,
                            SehirAd = "Sinop"
                        },
                        new
                        {
                            Id = 58,
                            BolgeId = 5,
                            Nufus = 621224,
                            SehirAd = "Sivas"
                        },
                        new
                        {
                            Id = 59,
                            BolgeId = 7,
                            Nufus = 972875,
                            SehirAd = "Tekirdağ"
                        },
                        new
                        {
                            Id = 60,
                            BolgeId = 6,
                            Nufus = 602662,
                            SehirAd = "Tokat"
                        },
                        new
                        {
                            Id = 61,
                            BolgeId = 6,
                            Nufus = 779379,
                            SehirAd = "Trabzon"
                        },
                        new
                        {
                            Id = 62,
                            BolgeId = 2,
                            Nufus = 82193,
                            SehirAd = "Tunceli"
                        },
                        new
                        {
                            Id = 63,
                            BolgeId = 4,
                            Nufus = 1940627,
                            SehirAd = "Şanlıurfa"
                        },
                        new
                        {
                            Id = 64,
                            BolgeId = 3,
                            Nufus = 358736,
                            SehirAd = "Uşak"
                        },
                        new
                        {
                            Id = 65,
                            BolgeId = 2,
                            Nufus = 1100190,
                            SehirAd = "Van"
                        },
                        new
                        {
                            Id = 66,
                            BolgeId = 5,
                            Nufus = 421041,
                            SehirAd = "Yozgat"
                        },
                        new
                        {
                            Id = 67,
                            BolgeId = 6,
                            Nufus = 597524,
                            SehirAd = "Zonguldak"
                        },
                        new
                        {
                            Id = 68,
                            BolgeId = 5,
                            Nufus = 396673,
                            SehirAd = "Aksaray"
                        },
                        new
                        {
                            Id = 69,
                            BolgeId = 6,
                            Nufus = 90154,
                            SehirAd = "Bayburt"
                        },
                        new
                        {
                            Id = 70,
                            BolgeId = 5,
                            Nufus = 245610,
                            SehirAd = "Karaman"
                        },
                        new
                        {
                            Id = 71,
                            BolgeId = 5,
                            Nufus = 277984,
                            SehirAd = "Kırıkkale"
                        },
                        new
                        {
                            Id = 72,
                            BolgeId = 4,
                            Nufus = 576899,
                            SehirAd = "Batman"
                        },
                        new
                        {
                            Id = 73,
                            BolgeId = 4,
                            Nufus = 483788,
                            SehirAd = "Şırnak"
                        },
                        new
                        {
                            Id = 74,
                            BolgeId = 6,
                            Nufus = 192389,
                            SehirAd = "Bartın"
                        },
                        new
                        {
                            Id = 75,
                            BolgeId = 2,
                            Nufus = 98335,
                            SehirAd = "Ardahan"
                        },
                        new
                        {
                            Id = 76,
                            BolgeId = 2,
                            Nufus = 192785,
                            SehirAd = "Iğdır"
                        },
                        new
                        {
                            Id = 77,
                            BolgeId = 7,
                            Nufus = 241665,
                            SehirAd = "Yalova"
                        },
                        new
                        {
                            Id = 78,
                            BolgeId = 6,
                            Nufus = 242347,
                            SehirAd = "Karabük"
                        },
                        new
                        {
                            Id = 79,
                            BolgeId = 4,
                            Nufus = 130825,
                            SehirAd = "Kilis"
                        },
                        new
                        {
                            Id = 80,
                            BolgeId = 1,
                            Nufus = 522175,
                            SehirAd = "Osmaniye"
                        },
                        new
                        {
                            Id = 81,
                            BolgeId = 6,
                            Nufus = 370371,
                            SehirAd = "Düzce"
                        });
                });

            modelBuilder.Entity("DoyaDoyaAnadolu.Data.Sehir", b =>
                {
                    b.HasOne("DoyaDoyaAnadolu.Data.Bolge", "Bolge")
                        .WithMany("Sehirler")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("DoyaDoyaAnadolu.Data.Bolge", b =>
                {
                    b.Navigation("Sehirler");
                });
#pragma warning restore 612, 618
        }
    }
}
